export const SECTOR_DATA = 'SECTOR_DATA'
export const CREATE_SECTOR_DATA = 'CREATE_SECTOR_DATA'
export const SET_SECTOR_DATA = 'SET_SECTOR_DATA'
export const DELETE_SECTOR_DATA = 'DELETE_SECTOR_DATA'
