export const CURRENCY_DATA = 'CURRENCY_DATA'
export const CREATE_CURRENCY_DATA = 'CREATE_CURRENCY_DATA'
export const SET_CURRENCY_DATA = 'SET_CURRENCY_DATA'
export const DELETE_CURRENCY_DATA = 'DELETE_CURRENCY_DATA'
