export const QUARTAL_DATA = 'QUARTAL_DATA'
export const CREATE_QUARTAL_DATA = 'CREATE_QUARTAL_DATA'
export const SET_QUARTAL_DATA = 'SET_QUARTAL_DATA'
export const DELETE_QUARTAL_DATA = 'DELETE_QUARTAL_DATA'
